### ISSUE TITLE
Platforms file referencing

### ISSUE THREAD

**Issue by uxebu** [uxebu/embedjs#2]
Atm it seems as if the feature => implementation mapping happens based on the embedjs dir. So new features residing in a different directort (a sibling of embedjs for instance) have to get referenced like this:

"feature": ["../app/feature.js"]

Not exactly sure if this is good or bad, maybe setting a basePath would be an option or always expect the root to be the parent of embedjs.

**Comment by jensarps** [comment]
As of 0.2, a base path can be set, and every file reference in the implementation map is relative to the base url set in the config.
