### ISSUE TITLE
Location of platforms and profile files

### ISSUE THREAD

**Issue by uxebu** [uxebu/embedjs#5]
Right now the platform and profile definitions are located outside of the src directory which makes it impossible to use them dynamically via JavaScript when using a dynamic loader and /src is the root dir. It might be good to have a dedicated dir within the src directory

**Comment by jensarps** [comment]
Platform files (= implementation maps) are still outside of of the src directory, but they don't have to be, one can put them wherever one wants to. However, we'll keep the structure for the repo, as the src directory should only contains actual feature implementations.

Same goes for profile files – put them wherever you want, but they are no _real_ source files, but mere helpers for stuff like the build process.
