### ISSUE TITLE
create hidden node

### ISSUE THREAD

**Issue by michalharakal** [uxebu/embedjs#7]
This in dojo creates an hidden input

``` javascript
   // create hidden input 
   var inp = dojo.create("input", {
                class: "edit",
                style: "display:none",
                type:"text", 
                value:"input value"},
                parentNode, "after"); 
```

Embedjs sets no style attribute. Is the style with embedjs ignored?
as workaround helps just setup the style manually:

``` javascript
   inp.style.display = "none";   
```

**Comment by jensarps** [comment]
Thanks for reporting this one. Right now, style (and event conenctions) is not supported by embed.create(). We did this to reduce dependencies from the create feature to other features, but we will re-consider this decision for a later release. For now, the way you propose is the only one. To prevent the element from flashing, I'd recommend to prepend the element only after style has been applied, like so:

  // create
  var element = embed.create('tagname', options)
  // style
  embed.style(element, styleOptions)
  // append
  parentNode.appendChild(element)

**Comment by jensarps** [comment]
As of 0.2, style is supported by embed.create(), but you need to hand over an object to embed.create, like so:

``` javascript
var inp = dojo.create('input', {
    class: 'edit',
    style: {
        display: 'none'
    },
    type: 'text', 
    value: 'input value'
},
parentNode, 'after'); 
```
